apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  annotations:
    harness.io/direct-apply: "true"
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
